routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

// rota para a página inicial do projeto 
Route::get('/', function () {
    return view('welcome');
});

// rota para a página de teste
Route::get('admin', function () {
    return view('admin_template');
});

//rota para home (criado pelo laravel auth)
Route::get('/home', 'HomeController@index')->name('home');

// rota para  o painel de controle
Route::resource('painel', 'PainelController');

// rota para o admin teste
Route::get('/admin2',['uses'=>'TesteController@index']); 


//Rota para usuários
Route::resource('usuarios', 'UsuarioController');
//Rota para  categorias de notícias
Route::resource('categorias', 'CategoriaController');
//Rota para notícias
Route::resource('noticias', 'NoticiaController');


// Rota para a página sobre
Route::get('/sobre', 'PainelController@sobre')->name('sobre');

app/Noticia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Noticia extends Model
{
    protected $primaryKey = 'id';
	protected $fillable   = [ 
		'texto',
		'situacao',
		'id_categoria',

	];


    public function categoria(){
        return $this->hasOne('App\Categoria', 'id', 'id_categoria');
    } 



}

app/Http/Controllers/NoticiaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Noticia;
use App\Categoria;

use DB;


class NoticiaController extends Controller
{
     public function __construct()
	{
	    $this->middleware('auth');
	}

	//lista todas as notícias
    public function index() {
    	 $registro = Noticia::all();
     	return view('noticias.listar',compact('registro'));
     }


     public function create(){

		$categoria     = Categoria::orderBy('descricao', 'asc')->pluck('descricao','id');

		return view("noticias.criar_editar", compact('categoria'));
	}

// insere notícia
	public function store(Request $request){
        
          //  dd($request);
       
         try {
            DB::beginTransaction();

            Noticia::create([
            'texto' => $request['texto'],
            'situacao' => $request['situacao'],
            'id_categoria' => $request['id_categoria']
        ]);

        } catch (\Illuminate\Database\QueryException $e) {
            DB::rollBack();
            return redirect()->route('noticias.index')->with('error','Não foi possível cadastrar!');
        }            

            DB::commit();
            return redirect()->route('noticias.index')->with('notice', 'Notícia Cadastrada!'); 
    }

	// editar dados da notícia
	public function edit($id){
		$noticia  = Noticia::find($id);
		$categoria     = Categoria::orderBy('descricao', 'asc')->pluck('descricao','id');
     	return view('noticias.criar_editar',compact('noticia','categoria'));

	}


	// altera os dados da notícia 
	 public function update(Request $request, $id){
	
		$noticia = Noticia::find($id);
		$noticia->texto = $request->get('texto');
        $noticia->situacao = $request->get('situacao');
        $noticia->id_categoria = $request->get('id_categoria');


	 	try {
	 		 $noticia->save();

        } catch (\Illuminate\Database\QueryException $e) {
            return redirect()->route('noticias.index')->with('error','Não foi possível alterar o registro!');
        }
        
        return redirect()->route('noticias.index')->with('notice', 'Registro Atualizado com Sucesso!');

    }

  // excluir  noticia
  	public function destroy($id){

        try {
            Noticia::find($id)->delete();
        } catch (\Illuminate\Database\QueryException $e) {
            return redirect()->route('noticias.index')->with('error','Não foi possível excluir o registro!');
        }
        
        return redirect()->route('noticias.index')->with('notice', 'Registro Excluído com Sucesso!');
    } 

}

resources/views/noticias/criar_editar.blade.php
@extends('tema.admin_template')

@section('titulo', 'Portal SI')

@section('titulo_conteudo', 'Notícias')

@section('breadcrumb')
<li class="active">Cadastro de Notícias</li>
@endsection

@section('acoes')
<a href="{{ route('noticias.index') }}" class="btn btn-sm btn-flat btn-default" data-toggle="tooltip" title="Voltar">
    <i class="fa fa-reply"></i> Voltar
</a>
@endsection


@section('conteudo')
@include('tema.mensagem')

@if(isset($noticia))
{!! Form::model($noticia, ['method' => 'PATCH', 'route' => ['noticias.update', $noticia->id]]) !!}
@else
{!! Form::model(new App\Noticia, ['route' => ['noticias.store']]) !!}

@endif

<div class="row">
    <div class="col-md-12">
        <div class="box box-solid">
            <div class="box-body">  
                <div class="row">
                    <div class="col-md-12">                     
                        
                        <div class="form-group">
                            {!! Form::label('situacao', 'Situação', array('class' => 'control-label')) !!}  
                            {!! Form::select('situacao', ['Ativa' => 'Ativa', 'Inativa' => 'Inativa'] ,null, array('class' => 'form-control', 'required')) !!}
                        </div> 


                        <div class="form-group {{ ($errors->has('texto') ? 'has-error' : null ) }}">
                            {!! Form::label('texto', 'Postagem', array('class' => 'control-label')) !!}   
                            {!! $errors->first('texto', '<span class="text-danger"> ( :message )</span>') !!} 
                            {!! Form::textarea('texto', null, array('class' => 'form-control ', 'placeholder' => 'Postagem', 'style' => 'width:100%;', 'required')) !!}
                        </div>  

                        <div class="form-group ">
                            {!! Form::label('id_categoria', 'Categoria da Notícia', array('class' => 'control-label')) !!}   
                            {!! Form::select('id_categoria', $categoria, null, ['class' => 'form-control select']) !!}
                        </div>  
                    </div>        
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" data-toggle="tooltip" title="Salvar" class="btn btn-flat btn-sm btn-success pull-right">
                    <i class="fa fa-save"></i> Salvar
                </button>
            </div>            
        </div>
    </div>
</div>

{!! Form::close() !!}

@endsection






    
 

resources/views/noticias/listar.blade.php
@extends('tema.admin_template')

@section('titulo') 
Projeto SI 
@stop

@section('titulo_conteudo')
Notícias
@stop

@section('breadcrumb')
<li class="active">Notícias</li>
@endsection

@section('acoes')
<a href="{{ route('noticias.create') }}" class="btn btn-flat btn-sm btn-primary" data-toggle="tooltip" title="Novo">
    <i class="fa fa-plus"></i> Novo
</a>
<a href="{{ route('painel.index') }}" class="btn btn-sm btn-flat btn-default" data-toggle="tooltip" title="Voltar">
  <i class="fa fa-reply"></i> Voltar
</a>
@endsection


@section('conteudo')

    <div class="row">
       <div class="col-md-12">
       @include('tema.mensagem')
           <div class="box box-solid">   
               <div class="box-body table-responsive">     
                   <table id="tnoticias" class="table table-bordered table-hover dataTable dt-responsive nowrap">
                       <thead>
                           <tr>
                               <th>#</th>
                               <th>Texto</th>
                               <th>Data</th>
                               <th>Categoria</th>
                               <th>Situação</th>

                               <th class="text-right no-print">Ações</th>
                           </tr>
                       </thead>
                       <tbody>
                           @foreach($registro  as $r)
                               <tr>
                                   <td>{{ $r->id }}</td>
                                   <td>{{ $r->texto }}</td>
                                   <td>{{ $r->data }}</td>
                                   <td>{{ $r->categoria->descricao }}</td>
                                   <td>{{ $r->situacao}}</td>

                                   <td class="text-right">

                                   {!! Form::open(['route' => ['noticias.destroy', $r->id], 'method' => 'DELETE', 'onsubmit' => 'return confirm("Excluir o Registro ?")' ]) !!}

                                   <a href="{{ route('noticias.edit', $r->id) }}" class="btn btn-flat btn-sm btn-primary" data-toggle="tooltip" title="Editar">
                                       <i class="fa fa-pencil"></i>
                                   </a>
                                   <button type="submit" class="delete btn btn-sm btn-flat btn-danger" data-toggle="tooltip" title="Excluir">
                                       <i class="fa fa-trash"></i>
                                   </button>  

                                   {!! Form::close() !!}
                                   </td> 


                               </tr>
                           @endforeach
                       </tbody>
                   </table>
               </div>
           </div>
       </div>
   </div>

@endsection