routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

// rota para a página inicial do projeto 
Route::get('/', function () {
    return view('welcome');
});

// rota para a página de teste
Route::get('admin', function () {
    return view('admin_template');
});

//rota para home (criado pelo laravel auth)
Route::get('/home', 'HomeController@index')->name('home');

// rota para  o painel de controle
Route::resource('painel', 'PainelController');

// rota para o admin teste
Route::get('/admin2',['uses'=>'TesteController@index']); 


//Rota para usuários
Route::resource('usuarios', 'UsuarioController');
//Rota para  categorias de notícias
Route::resource('categorias', 'CategoriaController');
//Rota para notícias
Route::resource('noticias', 'NoticiaController');


// Rota para a página sobre
Route::get('/sobre', 'PainelController@sobre')->name('sobre');

resources/views/tema/admin_template.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>PortalSI | UFSM FW</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link href="{{ asset("/bower_components/bootstrap/dist/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
  <!-- Font Awesome -->
   <link href="{{ asset("/bower_components/font-awesome/css/font-awesome.min.css") }}" rel="stylesheet" type="text/css" />
  <!-- Ionicons -->
    <link href="{{ asset("/bower_components/Ionicons/css/ionicons.min.css") }}" rel="stylesheet" type="text/css" />
  <!-- Theme style -->
   <link href="{{ asset("/bower_components/admin-lte/dist/css/AdminLTE.min.css") }}" rel="stylesheet" type="text/css" />
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
   
  <!-- <link href="{{ asset("/bower_components/admin-lte/dist/css/skins/skin-blue.min.css") }}" rel="stylesheet" type="text/css" /> -->
   <link href="{{ asset("/bower_components/admin-lte/dist/css/skins/skin-green.min.css") }}" rel="stylesheet" type="text/css" />

     <!--  <link href="{{ asset("/bower_components/admin-lte/dist/css/skins/skin-yellow.min.css") }}" rel="stylesheet" type="text/css" /> -->



  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-green sidebar-mini">
<!-- Main Header -->
    @include('tema.cabecalho')
  <!-- Left side column. contains the logo and sidebar -->
    @include('tema.menu')
<!-- Conteúdo -->    
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        @yield('titulo_conteudo')
      </h1>

      <div class="btn-acoes pull-right">
        @yield('acoes')
      </div>  
    </section>

    <section class="breadcrumbs">
      <ol class="breadcrumb">
        <li><a href="painel">Painel</a></li>
        @yield('breadcrumb')
      </ol>
    </section>

    <section class="content">
      @yield('conteudo')
    </section>
  </div>
  <!-- /.Conteúdo --> 


  <!-- Main Footer -->
  @include('tema.rodape')

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="pull-right-container">
                    <span class="label label-danger pull-right">70%</span>
                  </span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="{{ asset ("/bower_components/jquery/dist/jquery.min.js") }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset ("/bower_components/bootstrap/dist/js/bootstrap.min.js") }}"></script>

<!-- AdminLTE App -->
<script src="{{ asset ("/bower_components/admin-lte/dist/js/adminlte.min.js") }}"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>

resources/views/tema/cabecalho.blade.php
<header class="main-header">
    <a href="#" class="logo">
        <span class="logo-mini"><b>SI</b></span>
        <span class="logo-lg"><b>PortalSI</b></span>
    </a>

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Menu</span>
        </a>

    <div class="navbar-custom-menu">    
               <ul class="nav navbar-nav">

                   <li class="dropdown user user-menu">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                          <!--  <img src="#" class="user-image" alt="{{ Auth::user()->name }}">-->
                           <span class="hidden-xs">{{ Auth::user()->name }}</span>
                       </a>

                       <ul class="dropdown-menu">
                            <li class="user-header">            
                              <!--  <img src="#" class="img-circle" alt="{{ Auth::user()->name }}"> -->
                               <p>
                                   {{ Auth::user()->name }}
                                   <small>Usuário desde: {{ Auth::user()->created_at }}</small>
                               </p>
                           </li>
                           <li class="user-footer">
                               <div class="pull-left">
                                   <a href="#" class="btn btn-default btn-flat">Perfil</a>
                               </div>
                               <div class="pull-right">
                                   <a href="{{ route('logout') }}"
                                               onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">
                                               Sair
                                           </a>

                                           <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                               {{ csrf_field() }}
                                           </form>
                               </div>
                           </li>


                       </ul>
                   </li>
               </ul>
           </div>
    </nav>
</header>

resources/views/tema/mensagem.blade.php
@if (Session::get('notice'))
<div class="alert alert-success">
 <i class="fa fa-check"></i>
 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
 {!! Session::get('notice') !!}
</div>
@endif 

@if (Session::get('error'))
<div class="alert alert-danger">
 <i class="fa fa-ban"></i>
 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>                  
 {!! Session::get('error') !!}
</div>
@endif

@if (count($errors) > 0)
<div class="alert alert-danger">
    <i class="fa fa-ban"></i>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>                  
    Não foi possível realizar a operação.
    @foreach($errors->all() as $error)
  		<li>{!!$error!!}</li>
  	@endforeach
</div>
@endif

resources/views/tema/menu.blade.php
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Menu Principal</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="{{ route('painel.index') }}"><i class="fa fa-home"></i> <span>Início</span></a></li>
        <li><a href="{{ route('usuarios.index') }}"><i class="fa fa-user"></i> <span>Usuários</span></a></li>
        
        <li class="treeview">
          <a href="#"><i class="fa fa-newspaper-o"></i> <span>Notícias</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ route('noticias.index') }}">Listar</a></li>
            <li><a href="{{ route('categorias.index') }}">Categorias</a></li>
          </ul>
        </li>
        
        <li><a href="/sobre"><i class="fa fa-info-circle"></i> <span>Sobre</span></a></li>



      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

resources/views/tema/rodape.blade.php
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Portal SI
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2018 <a href="#">UFSM</a>.</strong> Todos os direitos reservados.
  </footer>