routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

// rota para a página inicial do projeto 
Route::get('/', function () {
    return view('welcome');
});

// rota para a página de teste
Route::get('admin', function () {
    return view('admin_template');
});

//rota para home (criado pelo laravel auth)
Route::get('/home', 'HomeController@index')->name('home');

// rota para  o painel de controle
Route::resource('painel', 'PainelController');

// rota para o admin teste
Route::get('/admin2',['uses'=>'TesteController@index']); 


//Rota para usuários
Route::resource('usuarios', 'UsuarioController');
//Rota para  categorias de notícias
Route::resource('categorias', 'CategoriaController');
//Rota para notícias
Route::resource('noticias', 'NoticiaController');


// Rota para a página sobre
Route::get('/sobre', 'PainelController@sobre')->name('sobre');

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


use App\User;
use App\Http\Requests\RequestUsuario;
use DB;


class UsuarioController extends Controller
{

	 /**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
	    $this->middleware('auth');
	}
    
//lista todos os usuários registrados e retorna para view
    public function index() {
    	 $registro = User::all();
     	return view('usuarios.listar',compact('registro'));
     }

// criar usuário
    public function create()
    {

        return view("usuarios.criar");

    }


    public function store(RequestUsuario $request){
   /// dd($request);
        try {
            DB::beginTransaction();

            User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password']),
        ]);

        } catch (\Illuminate\Database\QueryException $e) {
            DB::rollBack();
            return redirect()->route('usuarios.index')->with('error','Não foi possível cadastrar!');
        }            

            DB::commit();
            return redirect()->route('usuarios.index')->with('notice', 'Usuário Cadastrado!');
    }


// excluir usuário
  	public function destroy($id){

        try {
            User::find($id)->delete();
        } catch (\Illuminate\Database\QueryException $e) {
            return redirect()->route('usuarios.index')->with('error','Não foi possível excluir o registro!');
        }
        
        return redirect()->route('usuarios.index')->with('notice', 'Registro Excluído com Sucesso!');
    } 


	// editar dados do usuário
	public function edit($id){
		$usuario  = User::find($id);
        return view('usuarios.editar',compact('usuario'));

	}


	// altera os dados do usuario 
	 public function update(Request $request, $id){
	
		$usuario = User::find($id);
		$usuario->name=$request->get('name');
		$usuario->email=$request->get('email');
                $usuario->password= bcrypt($request->get('password'));

	 	try {
                $usuario->save();

        } catch (\Illuminate\Database\QueryException $e) {
            return redirect()->route('usuarios.index')->with('error','Não foi possível alterar o registro!');
        }
        
        return redirect()->route('usuarios.index')->with('notice', 'Registro Atualizado com Sucesso!');

    }


}

resources/views/usuarios/criar.blade.php
@extends('tema.admin_template')

@section('titulo', 'Usuários')

@section('titulo_conteudo', 'Cadastrar Usuário')

@section('breadcrumb')
<li class="active">Cadastrar Usuário</li>
@endsection

@section('acoes')
<a href="{{ route('usuarios.index') }}" class="btn btn-sm btn-flat btn-default" data-toggle="tooltip" title="Voltar">
    <i class="fa fa-reply"></i> Voltar
</a>
@endsection

@section('conteudo')
<div class="row">
    <div class="col-md-12">
        <div class="box box-solid">
            <div class="box-body">
              @include('tema.mensagem')

                {!! Form::open(['method' => 'POST', 'route' => ['usuarios.store']]) !!}

                    @include('usuarios.formulario')

                {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/usuarios/editar.blade.php
@extends('tema.admin_template')

@section('titulo', 'Portal do TSI - Usuários')

@section('titulo_conteudo', 'Atualizar Usuário')

@section('breadcrumb')
<li class="active">Editar Usuário</li>
@endsection

@section('acoes')
<a href="{{ route('usuarios.index') }}" class="btn btn-sm btn-flat btn-default" data-toggle="tooltip" title="Voltar">
    <i class="fa fa-reply"></i> Voltar
</a>

@section('conteudo')
<div class="row">
    <div class="col-md-12">
        <div class="box box-solid">
            <div class="box-body">
              @include('tema.mensagem')

                {!! Form::model($usuario, ['method' => 'PATCH', 'route' => ['usuarios.update', $usuario->id] ]) !!}

                    @include('usuarios.formulario')

                {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/usuarios/formulario.blade.php
<div class="form-group ">
    {!! Form::label('nome', 'Nome', array('class' => 'control-label')) !!}  
    {{ Form::text('name', old('name'), array('class' => 'form-control', 'placeholder' => 'nome', 'autofocus' => 'true', 'required')) }} 
</div>

<div class="form-group">
    {!! Form::label('email', 'E-mail', array('class' => 'control-label')) !!}     
    <div class="input-group">
        <span class="input-group-addon">
            <i class="fa fa-envelope"></i>
        </span>
        {{ Form::email('email', old('email'), array('class' => 'form-control', 'placeholder' => 'e-mail', 'style' => 'text-transform:lowercase;', 'required')) }}
    </div> 
</div>                          


<div class="form-group">
    {!! Form::label('password', 'Senha', array('class' => 'control-label')) !!} 

    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        {{ Form::password('password',  array('class' => 'form-control', 'id' =>'password', 'placeholder' => 'senha', 'required', 'minlength' => '6')) }} 
    </div>                             
</div>        

<div class="form-group">
    {!! Form::label('confirmacao_senha', 'Confirmar senha', array('class' => 'control-label')) !!}  
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        {!! Form::password('password_confirmation', array('class' => 'form-control','placeholder' => 'Confirmar senha', 'minlength' => '6')) !!}

    </div>  
</div> 


</div>
<div class="box-footer">
<button type="submit" data-toggle="tooltip" title="Salvar" class="btn btn-flat btn-sm btn-success pull-right">
    <i class="fa fa-save"></i> Salvar
</button>
</div>   

resources/views/usuarios/listar.blade.php
@extends('tema.admin_template')

@section('titulo', 'Usuários')

@section('titulo_conteudo', 'Usuários Registrados')

@section('breadcrumb')
<li class="active">Usuários Registrados</li>
@endsection


@section('acoes')
<a href="{{ route('usuarios.create') }}" class="btn btn-flat btn-sm btn-primary" data-toggle="tooltip" title="Novo">
    <i class="fa fa-plus"></i> Novo
</a>
<a href="{{ route('painel.index') }}" class="btn btn-sm btn-flat btn-default" data-toggle="tooltip" title="Voltar">
  <i class="fa fa-reply"></i> Voltar
</a>
@endsection

@section('conteudo')

 <div class="row">
    <div class="col-md-12">
    @include('tema.mensagem')
        <div class="box box-solid">   
            <div class="box-body table-responsive">     
                <table   class="table table-bordered table-hover dataTable dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th>Data de Registro</th>

                            <th class="text-right no-print">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($registro  as $r)
                            <tr>
                                <td>{{ $r->id }}</td>
                                <td>{{ $r->name }}</td>
                                <td>{{ $r->email }}</td>
                                <td>{{ $r->created_at }}</td>

                                <td class="text-right">

                                {!! Form::open(['route' => ['usuarios.destroy', $r->id], 'method' => 'DELETE', 'onsubmit' => 'return confirm("Excluir o Registro ?")' ]) !!}

                                <a href="{{ route('usuarios.edit', $r->id) }}" class="btn btn-flat btn-sm btn-primary" data-toggle="tooltip" title="Editar">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                @if(Auth::id() != $r->id)
                                <button type="submit" class="delete btn btn-sm btn-flat btn-danger" data-toggle="tooltip" title="Excluir">
                                    <i class="fa fa-trash"></i>
                                </button>  
                                @endif 

                                {!! Form::close() !!}
                                </td> 
                                    

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection