routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

// rota para a página inicial do projeto 
Route::get('/', function () {
    return view('welcome');
});

// rota para a página de teste
Route::get('admin', function () {
    return view('admin_template');
});

//rota para home (criado pelo laravel auth)
Route::get('/home', 'HomeController@index')->name('home');

// rota para  o painel de controle
Route::resource('painel', 'PainelController');

// rota para o admin teste
Route::get('/admin2',['uses'=>'TesteController@index']); 


//Rota para usuários
Route::resource('usuarios', 'UsuarioController');
//Rota para  categorias de notícias
Route::resource('categorias', 'CategoriaController');
//Rota para notícias
Route::resource('noticias', 'NoticiaController');


// Rota para a página sobre
Route::get('/sobre', 'PainelController@sobre')->name('sobre');

app/Categoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    protected $table = 'categorias';

	protected $fillable = [
	'descricao'
	];	
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Categoria;
use App\Http\Requests\RequestCategoria;

class CategoriaController extends Controller
{
    public function __construct()
	{
	    $this->middleware('auth');
	}


 
    public function index() {
    	$registro = Categoria::all();
     	return view('categorias.listar',compact('registro'));
     }
     

    public function create()
    {
    	return view("categorias.criar_editar");
      
    }

	public function store(RequestCategoria $request){
       try {
            DB::beginTransaction();

            Categoria::create($request->all());

        } catch (\Illuminate\Database\QueryException $e) {
            DB::rollBack();
            return back()->with('error','Não foi possível cadastrar!');

        }            

            DB::commit();
            return redirect()->route('categorias.index')->with('notice', 'Registro  Cadastrado com Sucessso!'); 
    }


	public function edit($id){
		$registro  = Categoria::find($id);
     	return view('categorias.criar_editar',compact('registro')); 

	}


	 public function update(RequestCategoria $request, $id){
	
		$categoria = Categoria::find($id);
		$categoria->descricao=$request->get('descricao');


	 	try {
	 		 $categoria->save();

        } catch (\Illuminate\Database\QueryException $e) {
            return back()->with('error','Não foi possível alterar o registro!');
        }
        
        return redirect()->route('categorias.index')->with('notice', 'Registro Atualizado com Sucesso!');

    }



  	public function destroy($id){

        try {
            Categoria::find($id)->delete();
        } catch (\Illuminate\Database\QueryException $e) {
            return redirect()->route('categorias.index')->with('error','Não foi possível excluir o registro!');
        }
        
        return redirect()->route('categorias.index')->with('notice', 'Registro Excluído com Sucesso!'); 
    } 




}

resources/views/categorias/criar_editar.blade.php
@extends('tema.admin_template')

@section('titulo', 'Portal SI')

@section('titulo_conteudo', 'Categorias')

@section('breadcrumb')
<li class="active">Cadastro de Categorias</li>
@endsection

@section('acoes')
<a href="{{ route('categorias.index') }}" class="btn btn-sm btn-flat btn-default" data-toggle="tooltip" title="Voltar">
    <i class="fa fa-reply"></i> Voltar
</a>
@endsection


@section('conteudo')
@include('tema.mensagem')

@if(isset($registro))
{!! Form::model($registro, ['method' => 'PATCH', 'route' => ['categorias.update', $registro->id]]) !!}
@else
{!! Form::model(new App\Categoria, ['route' => ['categorias.store']]) !!}

@endif

<div class="row">
    <div class="col-md-12">
        <div class="box box-solid">
            <div class="box-body">  
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group {{ ($errors->has('descricao') ? 'has-error' : null ) }}">
                            {!! Form::label('descricao', 'Descrição', array('class' => 'control-label')) !!}  
                            {!! $errors->first('descricao', '<span class="text-danger"> ( :message )</span>') !!}    
                            {{ Form::text('descricao', old('descricao'), array('class' => 'form-control', 'placeholder' => 'Categoria', 'autofocus' => 'true', 'required')) }} 
                        </div>                        
                    </div>        
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" data-toggle="tooltip" title="Salvar" class="btn btn-flat btn-sm btn-success pull-right">
                    <i class="fa fa-save"></i> Salvar
                </button>
            </div>            
        </div>
    </div>
</div>

{!! Form::close() !!}

@endsection






    
 

resources/views/categorias/listar.blade.php
@extends('tema.admin_template')

@section('titulo') 
Projeto SI 
@stop

@section('titulo_conteudo')
Notícias
@stop

@section('breadcrumb')
<li class="active">Categorias</li>
@endsection

@section('acoes')
<a href="{{ route('categorias.create') }}" class="btn btn-flat btn-sm btn-primary" data-toggle="tooltip" title="Novo">
    <i class="fa fa-plus"></i> Novo
</a>
<a href="{{ route('painel.index') }}" class="btn btn-sm btn-flat btn-default" data-toggle="tooltip" title="Voltar">
  <i class="fa fa-reply"></i> Voltar
</a>
@endsection


@section('conteudo')

 <div class="row">
    <div class="col-md-12">
    @include('tema.mensagem')
        <div class="box box-solid">   
            <div class="box-body table-responsive">     
                <table class="table table-bordered table-hover dataTable dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Descrição</th>
                            <th>Data de Registro</th>
                            <th class="text-right no-print">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($registro  as $r)
                            <tr>
                                <td>{{ $r->id }}</td>
                                <td>{{ $r->descricao }}</td>
                                 <td>{{ $r->created_at }}</td>
                                <td class="text-right">

                                {!! Form::open(['route' => ['categorias.destroy', $r->id], 'method' => 'DELETE','onsubmit' => 'return confirm("Excluir o Registro ?")' ]) !!}

                                <a href="{{ route('categorias.edit', $r->id) }}" class="btn btn-flat btn-sm btn-primary" data-toggle="tooltip" title="Editar">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <button type="submit" class="delete btn btn-sm btn-flat btn-danger" data-toggle="tooltip" title="Excluir">
                                    <i class="fa fa-trash"></i>
                                </button>  

                                {!! Form::close() !!}
                                </td> 
                                    

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

 